// File generated by Antigravity (Assistant)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Android is handled automatically by google-services.json
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPGlqDXjE-E-CvahVIf4bU2XEhq5wcqY',
    appId: '1:511739624605:web:0e5a5652d24e557a6e6874',
    messagingSenderId: '511739624605',
    projectId: 'edulink-3a5b2',
    authDomain: 'edulink-3a5b2.firebaseapp.com',
    storageBucket: 'edulink-3a5b2.firebasestorage.app',
    measurementId: 'G-K8NS7Q5L5B',
  );
}
